version: '3'
services:
  postgres:
    image: postgres:17
    restart: always
    container_name: 'postgres-code_challenge_project'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: posts-db
    ports:
      - "5432:5432"
    networks:
      - code_challenge_project

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: 'pgadmin-code_challenge_project'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3000:80"
    depends_on:
      - postgres
    networks:
      - code_challenge_project

networks:
  code_challenge_project:
    driver: bridge
